feat(python): show properties and values in TypeBuilder string representation
BoundaryML/baml pull request #1260
Opened 2024-12-18 09:53 UTC by revidious

This PR enhances the TypeBuilder's string representation to show all properties of a class and values of an enum, including their aliases and descriptions.

Changes:
- Show all properties in class representation:
  ```python
  # Before:
  TypeBuilder(Classes: ['User'])
  
  # After:
  TypeBuilder(Classes: ['User { name (alias='username', desc='The user\'s full name'), age (desc='User\'s age in years'), email }'])
  ```

- Show all values in enum representation:
  ```python
  # Before:
  TypeBuilder(Enums: ['Status'])
  
  # After:
  TypeBuilder(Enums: ['Status { ACTIVE (alias='active', desc='User is active'), INACTIVE (alias='inactive'), PENDING }'])
  ```

- Store and track metadata:
  - Cache aliases and descriptions in builders
  - Sort properties and values for consistent output
  - Properly escape quotes in string values

Fixes #1253

2024-12-18 22:58 UTC, aaronvg commented
nice work! We'll have someone in the team review soon

2024-12-22 00:56 UTC, hellovai requested changes
@revidious this is really great work, but if possible, would you be ok implenting this in rust instead?

otherwise we'll have different printers in python/ts/ruby/etc and will make it harder to catch bugs later on (and small details will easily be missed)

2024-12-24 07:40 UTC, revidious commented
@hellovai Done! I've moved the implementation to Rust with the Display trait, and Python now just exposes it via __str__.

2024-12-24 18:11 UTC, hellovai requested changes
this is great! :) ready to merge. small request, could you add this for the language_client_{ts / ruby} as well. If not, let us know and i'll follow up on it instead. This is almost perfect btw 👍 

Some nits things I would do (but not mandatory): 
* add whitespace / newlines in the rendered string
* instead of `BamlValue::to_string(...)` I would just implement the display for all baml values
* Instead of hard-coding which attributes i print out for meta, i would inject all metas in the print out, not just alias / description

2024-12-25 10:56 UTC, revidious commented
Thanks for the feedback! I've implemented all three suggestions:
- Added proper whitespace/newlines in the rendered string
- Using BamlValue's Display trait directly instead of to_string()
- Now showing all metadata fields without specific ones

Changes are implemented in both TypeScript and Ruby clients as well (what it seems like).

2024-12-30 22:54 UTC, aaronvg commented
It seems there's some issues with:
"FAILED test_type_builder_str.py::test_type_builder_str - AttributeError: 'TypeBuilder' object has no attribute 'class_'"

If you can take a look, it seems this PR is close

2025-01-09 06:31 UTC, hellovai commented
hey @revidious! Just wanted to follow up here! Glad to fork this PR and make the fixes myself if you are busy. this is a great one and we'd love to merge this in!

2025-01-09 06:31 UTC, hellovai submitted a review, later dismissed
waiting for tests to pass

2025-01-10 12:13 UTC, revidious commented
Hey @hellovai! Thanks for following up. I’ve been a bit caught up with life and other things, but I really appreciate your offer to fork the PR and make the fixes yourself. I’ll try to get the tests sorted and the changes addressed soon. Thanks so much for your patience!

2025-02-14 22:09 UTC, aaronvg commented
@afyef amazing work! Got this one merged for you

2025-02-14 22:11 UTC, merged