Generic multimodal BAML type
BoundaryML/baml pull request #692
Opened 2024-06-19 03:49 UTC by anish-palakurthi

Currently supporting image and audio!
More to come!

2024-06-19 17:21 UTC, hellovai commented on integ-tests/baml_src/test-files/functions/input/named-args/single/named-audio.baml
split test case vs function into two files so only 1 file is excluded

2024-06-19 17:21 UTC, hellovai requested changes

2024-06-19 17:21 UTC, hellovai commented on integ-tests/python/test_functions.py
b64 should be a variable in a special file

2024-06-20 23:10 UTC, aaronvg commented on integ-tests/python/test_functions.py
>      stream = b.stream.MyFunc(
whys this called twice?

2024-06-20 23:13 UTC, anish-palakurthi commented on integ-tests/python/test_functions.py
>      stream = b.stream.MyFunc(
probably was from a merge. deleted it.

2024-06-20 23:13 UTC, aaronvg commented on engine/baml-runtime/src/internal/llm_client/primitive/openai/openai_client.rs
> +            // properties: $properties,
delete

2024-06-20 23:14 UTC, aaronvg commented on engine/baml-runtime/Cargo.toml
> +infer = "0.16.0"
can you fill me in on what these are used for?

2024-06-20 23:35 UTC, hellovai approved these changes

2024-06-20 23:35 UTC, merged